version: '3'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile-laravel
    container_name: laravel-container
    networks:
      - mi_red

  postgres-db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin2024#
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge

